"""hotel reservations replace dental booking

Revision ID: c7f5c2420a93
Revises: 368cbeb2e168
Create Date: 2026-05-30 12:10:14.303994+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f5c2420a93'
down_revision: Union[str, None] = '368cbeb2e168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('room_type', sa.String(length=128), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_check_in'), 'reservations', ['check_in'], unique=False)
    op.create_index(op.f('ix_reservations_workspace_id'), 'reservations', ['workspace_id'], unique=False)
    op.create_index('ix_reservations_ws_checkin', 'reservations', ['workspace_id', 'check_in'], unique=False)
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_workspace_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ws_start'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_booking_configs_workspace_id'), table_name='booking_configs')
    op.drop_table('booking_configs')
    op.drop_index(op.f('ix_providers_workspace_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('providers_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('providers_pkey'))
    )
    op.create_index(op.f('ix_providers_workspace_id'), 'providers', ['workspace_id'], unique=False)
    op.create_table('booking_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('slot_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('booking_configs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_configs_pkey'))
    )
    op.create_index(op.f('ix_booking_configs_workspace_id'), 'booking_configs', ['workspace_id'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patient_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('appointments_call_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('appointments_provider_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('appointments_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_ws_start'), 'appointments', ['workspace_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_workspace_id'), 'appointments', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.drop_index('ix_reservations_ws_checkin', table_name='reservations')
    op.drop_index(op.f('ix_reservations_workspace_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_in'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
