"""owner_user_id on calls and reservations

Revision ID: 9154ce66582e
Revises: c7f5c2420a93
Create Date: 2026-05-30 13:53:50.351607+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9154ce66582e'
down_revision: Union[str, None] = 'c7f5c2420a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calls_owner_user_id'), 'calls', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'calls', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('reservations', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservations_owner_user_id'), 'reservations', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_owner_user_id'), table_name='reservations')
    op.drop_column('reservations', 'owner_user_id')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_owner_user_id'), table_name='calls')
    op.drop_column('calls', 'owner_user_id')
    # ### end Alembic commands ###
