"""add providers

Revision ID: 368cbeb2e168
Revises: c560100bdde4
Create Date: 2026-05-30 11:57:29.535536+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368cbeb2e168'
down_revision: Union[str, None] = 'c560100bdde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_workspace_id'), 'providers', ['workspace_id'], unique=False)
    op.add_column('appointments', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'providers', ['provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_column('appointments', 'provider_id')
    op.drop_index(op.f('ix_providers_workspace_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
